use chrono::{DateTime, Utc};
use printpdf::*;
use std::io::BufWriter;

use super::models::MetricResult;

// ============================================================
// CSV export
// ============================================================

/// Serialise one or more metric results to CSV bytes.
///
/// Watermark rows are prepended as comment-style lines so they survive
/// spreadsheet round-trips and are visible in plain-text viewers.
///
/// Layout:
///   # Generated by: <viewer_name>
///   # Generated at: <timestamp>
///   # (blank separator)
///   metric_key,display_name,unit,period_start,period_end,value,sample_count
///   ...rows...
pub fn to_csv(
    results:     &[MetricResult],
    viewer_name: &str,
    generated_at: DateTime<Utc>,
) -> Result<Vec<u8>, String> {
    let mut buf = Vec::<u8>::new();

    // Watermark header
    let header = format!(
        "# Generated by: {}\n# Generated at: {}\n#\n",
        viewer_name,
        generated_at.format("%Y-%m-%dT%H:%M:%SZ"),
    );
    buf.extend_from_slice(header.as_bytes());

    // CSV body
    let mut wtr = csv::Writer::from_writer(&mut buf);
    wtr.write_record(&[
        "metric_key",
        "display_name",
        "unit",
        "period_start",
        "period_end",
        "value",
        "sample_count",
    ])
    .map_err(|e| e.to_string())?;

    for result in results {
        for point in &result.series {
            wtr.write_record(&[
                &result.metric_key,
                &result.display_name,
                &result.unit,
                &point.period_start.format("%Y-%m-%dT%H:%M:%SZ").to_string(),
                &point.period_end.format("%Y-%m-%dT%H:%M:%SZ").to_string(),
                &format!("{:.4}", point.value),
                &point.sample_count.to_string(),
            ])
            .map_err(|e| e.to_string())?;
        }
    }

    wtr.flush().map_err(|e| e.to_string())?;
    drop(wtr);

    Ok(buf)
}

// ============================================================
// PDF export
// ============================================================

/// Render metric results to a PDF document in memory.
///
/// Layout per metric:
///   - Section heading (metric display_name + unit)
///   - One line per time-series data point
///   - Summary statistics block
///
/// A diagonal watermark of the form
///   "<viewer_name>  |  <timestamp>"
/// is stamped across every page in light grey.
pub fn to_pdf(
    results:      &[MetricResult],
    viewer_name:  &str,
    generated_at: DateTime<Utc>,
) -> Result<Vec<u8>, String> {
    let (doc, page1, layer1) =
        PdfDocument::new("TransitOps KPI Report", Mm(210.0), Mm(297.0), "Layer 1");

    let font = doc
        .add_builtin_font(BuiltinFont::HelveticaBold)
        .map_err(|e| e.to_string())?;
    let font_regular = doc
        .add_builtin_font(BuiltinFont::Helvetica)
        .map_err(|e| e.to_string())?;

    // Watermark text — "<viewer>  |  <timestamp>"
    let watermark_text = format!(
        "{}  |  {}",
        viewer_name,
        generated_at.format("%Y-%m-%dT%H:%M:%SZ"),
    );

    // Page dimensions (A4 in mm)
    const PAGE_W: f32 = 210.0;
    const PAGE_H: f32 = 297.0;
    const MARGIN: f32 = 20.0;
    const LINE_H: f32 = 7.0;

    // ---- helper: stamp diagonal watermark ----
    // Uses begin/set_text_matrix/write_text/end so rotation is applied correctly.
    let stamp_watermark = |layer: &PdfLayerReference| {
        layer.set_fill_color(Color::Rgb(Rgb::new(0.85, 0.85, 0.85, None)));
        layer.begin_text_section();
        layer.set_font(&font_regular, 14.0);
        layer.set_text_matrix(TextMatrix::TranslateRotate(
            Pt((PAGE_W / 2.0 - 60.0).into()),
            Pt((PAGE_H / 2.0 - 20.0).into()),
            45.0,
        ));
        layer.write_text(watermark_text.clone(), &font_regular);
        layer.end_text_section();
        layer.set_fill_color(Color::Rgb(Rgb::new(0.0, 0.0, 0.0, None)));
    };

    // Track current page layer and Y cursor
    let mut current_layer = doc.get_page(page1).get_layer(layer1);
    let mut cursor_y: f32 = PAGE_H - MARGIN;
    stamp_watermark(&current_layer);

    // Macro: ensure N lines of space; breaks to a new page if not enough room.
    macro_rules! ensure_space {
        ($lines:expr) => {
            if cursor_y < MARGIN + ($lines as f32) * LINE_H {
                let (new_page, new_layer) = doc.add_page(Mm(PAGE_W), Mm(PAGE_H), "Layer 1");
                current_layer = doc.get_page(new_page).get_layer(new_layer);
                cursor_y = PAGE_H - MARGIN;
                stamp_watermark(&current_layer);
            }
        };
    }

    // ---- Document title ----
    ensure_space!(3);
    current_layer.use_text(
        "TransitOps KPI Report",
        16.0,
        Mm(MARGIN),
        Mm(cursor_y),
        &font,
    );
    cursor_y -= LINE_H * 1.5;

    current_layer.use_text(
        format!(
            "Generated by {} at {}",
            viewer_name,
            generated_at.format("%Y-%m-%d %H:%M UTC")
        ),
        9.0,
        Mm(MARGIN),
        Mm(cursor_y),
        &font_regular,
    );
    cursor_y -= LINE_H * 2.0;

    // ---- One section per metric ----
    for result in results {
        ensure_space!(4);

        current_layer.use_text(
            format!("{} ({})", result.display_name, result.unit),
            12.0,
            Mm(MARGIN),
            Mm(cursor_y),
            &font,
        );
        cursor_y -= LINE_H;

        ensure_space!(2);
        current_layer.use_text(
            format!("{:<28} {:>12} {:>14}", "Period Start", "Value", "Samples"),
            9.0,
            Mm(MARGIN),
            Mm(cursor_y),
            &font,
        );
        cursor_y -= LINE_H * 0.8;

        for point in &result.series {
            ensure_space!(1);
            let line = format!(
                "{:<28} {:>11.2} {:>14}",
                point.period_start.format("%Y-%m-%d %H:%M"),
                point.value,
                point.sample_count,
            );
            current_layer.use_text(line, 9.0, Mm(MARGIN), Mm(cursor_y), &font_regular);
            cursor_y -= LINE_H;
        }

        ensure_space!(3);
        cursor_y -= LINE_H * 0.5;
        current_layer.use_text(
            format!(
                "Summary  avg: {:.2}  min: {:.2}  max: {:.2}  samples: {}",
                result.summary.average,
                result.summary.min,
                result.summary.max,
                result.summary.total_samples,
            ),
            9.0,
            Mm(MARGIN),
            Mm(cursor_y),
            &font_regular,
        );
        cursor_y -= LINE_H * 2.0;
    }

    // Drop layer handle before serialising to avoid conflicting Arc references.
    drop(current_layer);

    let mut raw: Vec<u8> = Vec::new();
    {
        let mut writer = BufWriter::new(&mut raw);
        doc.save(&mut writer).map_err(|e| e.to_string())?;
    }
    Ok(raw)
}

// ============================================================
// Tests
// ============================================================
#[cfg(test)]
mod tests {
    use super::*;
    use super::super::models::TimeSeriesPoint;
    use chrono::TimeZone;

    fn make_result(key: &str, points: &[(f64, i64)]) -> MetricResult {
        let series: Vec<TimeSeriesPoint> = points
            .iter()
            .enumerate()
            .map(|(i, (v, n))| TimeSeriesPoint {
                period_start:  Utc.with_ymd_and_hms(2025, 1, 1 + i as u32, 0, 0, 0).unwrap(),
                period_end:    Utc.with_ymd_and_hms(2025, 1, 2 + i as u32, 0, 0, 0).unwrap(),
                value:         *v,
                sample_count:  *n,
            })
            .collect();
        let summary = crate::reporting::models::MetricSummary {
            total_samples: series.iter().map(|p| p.sample_count).sum(),
            average: if series.is_empty() { 0.0 } else {
                series.iter().map(|p| p.value).sum::<f64>() / series.len() as f64
            },
            min: series.iter().map(|p| p.value).fold(f64::INFINITY, f64::min),
            max: series.iter().map(|p| p.value).fold(f64::NEG_INFINITY, f64::max),
        };
        MetricResult {
            metric_key:   key.to_string(),
            display_name: key.to_string(),
            unit:         "%".to_string(),
            series,
            summary,
        }
    }

    #[test]
    fn csv_contains_watermark_and_header() {
        let ts = Utc.with_ymd_and_hms(2025, 6, 1, 12, 0, 0).unwrap();
        let r  = make_result("on_time_departure_rate", &[(95.0, 100), (87.0, 90)]);
        let bytes = to_csv(&[r], "Alice Smith", ts).unwrap();
        let text  = String::from_utf8(bytes).unwrap();

        assert!(text.contains("# Generated by: Alice Smith"));
        assert!(text.contains("# Generated at: 2025-06-01T12:00:00Z"));
        assert!(text.contains("metric_key"));
        assert!(text.contains("on_time_departure_rate"));
        assert!(text.contains("95.0000"));
    }

    #[test]
    fn csv_multiple_metrics() {
        let ts = Utc.with_ymd_and_hms(2025, 6, 1, 0, 0, 0).unwrap();
        let r1 = make_result("refund_rate",       &[(2.5, 400)]);
        let r2 = make_result("mismatch_count",    &[(3.0, 200)]);
        let bytes = to_csv(&[r1, r2], "Bob", ts).unwrap();
        let text  = String::from_utf8(bytes).unwrap();
        assert!(text.contains("refund_rate"));
        assert!(text.contains("mismatch_count"));
    }

    #[test]
    fn pdf_generates_non_empty_bytes() {
        let ts = Utc.with_ymd_and_hms(2025, 6, 1, 12, 0, 0).unwrap();
        let r  = make_result("on_time_departure_rate", &[(95.0, 100)]);
        let bytes = to_pdf(&[r], "Alice Smith", ts).unwrap();
        assert!(!bytes.is_empty());
        // PDFs start with the %PDF- magic bytes
        assert!(bytes.starts_with(b"%PDF-"));
    }
}
